### ISSUE TITLE
Lazy loading?

### ISSUE THREAD

**Issue by oyeanuj** [heydovetail/react-masonry-responsive#8]
Hey @humphreybc! Thanks for open sourcing this library! I'm wondering if there is a way to do lazy loading the children (especially since the masonry deals with the responsive mode). For example, on a mobile device, I'm hoping not to load all the children (which in my case are like Youtube embeds).

Do you think that should be part of the library? Or any other recommendations?

**Comment by humphreybc** [comment]
Hi @oyeanuj, you could use an intersection observer at the bottom of the items to load more as the user scrolls. We do something like this in Dovetail for lazy loading search results. Here's a relevant snippet of code that might get you started:

```typescript
<div
  ref={el => {
    if (el !== null) {
      try {
        this.intersectionObserver = new IntersectionObserver(
          ([entry]) => {
            if (entry.isIntersecting) {
              this.props.loadMore();
            }
          },
          { threshold: 0.5, root: null, rootMargin: "1000px" }
        );
        this.intersectionObserver.observe(el);
      } catch {
        // IntersectionObserver may not be supported.
      }
    } else if (this.intersectionObserver !== undefined) {
      this.intersectionObserver.disconnect();
      this.intersectionObserver = undefined;
    }
  }}
/>
```
